# @license BSD-3 https://opensource.org/licenses/BSD-3-Clause
# Copyright (c) 2022, Institute of Automatic Control - RWTH Aachen University
# All rights reserved.

default:
  image: julia:latest
  before_script:
    - apt update && apt install -y xvfb
    # Add repo dependencies
    - sed -i "s|https://git-ce.|https://gitlab-ci-token:$CI_JOB_TOKEN@git-ce.|g" Manifest.toml
    - xvfb-run -a julia --project=@. -e 'import Pkg; Pkg.instantiate(); Pkg.build();'

test:
  stage: test
  script:
    - apt update && apt install -y python3-pip lcov
    - pip install lcov_cobertura
    - xvfb-run -a julia --project=@. -e 'using Pkg; Pkg.add("LocalCoverage"); using LocalCoverage; cov = generate_coverage("SciGL"; run_test = true); generate_xml(cov, "coverage.xml"); html_coverage(cov; dir="coverage_html"); report_coverage_and_exit(cov; target_coverage=70);'
  coverage: '/TOTAL.*│\s*(\d+)\%/'
  artifacts:
    paths:
      - coverage/coverage.xml
      - coverage_html
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml

pages:
  stage: deploy
  script:
    - xvfb-run -a  julia --project=docs -e 'import Pkg; Pkg.develop(path=pwd()); Pkg.instantiate();'
    - xvfb-run -a  julia --project=docs --color=yes docs/make.jl
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - main
